canBePaid on gateway
souzamarcos/tech-challenge-fast-food pull request #38
Opened 2023-10-13 18:39 UTC by victoroliveira93

Mudando o canBePaid para o orderGateway

2023-10-14 20:52 UTC, souzamarcos requested changes

2023-10-14 20:52 UTC, souzamarcos commented on application/src/main/java/com/fiap/burger/application/config/ApplicationConfiguration.java
> +        return new DefaultPaymentUseCase(paymentGateway, new DefaultOrderGateway());
Não há necessidade de instanciar um `new DefaultOrderGateway()` o Spring irá injetar a implementação da interface OrderGateway, ou seja, será criado um `DefaultOrderGateway  `se fizer no exemplo abaixo.
```suggestion
    public PaymentUseCase paymentUseCase(PaymentGateway paymentGateway, OrderGateway orderGateway) {
        return new DefaultPaymentUseCase(paymentGateway, orderGateway);
```

2023-10-14 20:52 UTC, souzamarcos commented on entity/src/main/java/com/fiap/burger/entity/order/Order.java
> +    }
Não deveria ser o status do pedido a ser considerado? Ao invés de usar um status vindo por parâmetro?
```suggestion
    public static boolean canBePaid() {
        return OrderStatus.AGUARDANDO_PAGAMENTO.equals(this.status);
    }
```

2023-10-14 20:52 UTC, souzamarcos commented on usecase/src/main/java/com/fiap/burger/usecase/usecase/DefaultPaymentUseCase.java
> +        if (!orderGateway.canBePaid(order.getStatus())) {
Como a função `order.canBePaid` já existe, não precisa de um método canBePaid em `orderGateway`.
```suggestion
        if (!order.canBePaid()) {
```

2023-10-14 20:52 UTC, souzamarcos commented on usecase/src/main/java/com/fiap/burger/usecase/usecase/DefaultPaymentUseCase.java
>              case RECUSADO -> orderUseCase.updateStatus(persistedPayment.getOrder().getId(), OrderStatus.CANCELADO);
Algum motivo pro comentário?

2023-10-14 21:00 UTC, souzamarcos commented on usecase/src/main/java/com/fiap/burger/usecase/usecase/DefaultPaymentUseCase.java
> +        /*
Algum motivo pro comentário?

2023-10-15 00:41 UTC, victoroliveira93 reviewed
correcoes feitas

2023-10-29 17:19 UTC, souzamarcos approved these changes

2023-10-29 17:42 UTC, merged